# Generated by Django 5.2.17 on 2026-08-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsanalysis",
            name="sender",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="smsanalysis",
            name="user_feedback",
            field=models.CharField(
                blank=True,
                choices=[
                    ("correct", "Correct"),
                    ("false_positive", "Faux positif"),
                    ("false_negative", "Faux négatif"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
