# Generated by Django 5.2.17 on 2026-08-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detector", "0002_smsanalysis_sender_smsanalysis_user_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=64)),
                ("amount", models.FloatField()),
                ("risk_score", models.IntegerField()),
                ("label", models.CharField(max_length=20)),
                ("reasons", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
